export const placeTypeMap: { [key: string]: string } = {
  // 🚗 자동차 관련
  car_dealer: '자동차 대리점',
  car_rental: '렌터카',
  car_repair: '자동차 수리',
  car_wash: '세차장',
  electric_vehicle_charging_station: '전기차 충전소',
  gas_station: '주유소',
  parking: '주차장',
  rest_stop: '휴게소',

  // 🏢 비즈니스
  corporate_office: '회사 사무실',
  farm: '농장',
  ranch: '목장',

  // 🏛️ 문화
  art_gallery: '미술관',
  art_studio: '아트 스튜디오',
  auditorium: '강당',
  cultural_landmark: '문화 유적지',
  historical_place: '역사적 장소',
  monument: '기념물',
  museum: '박물관',
  performing_arts_theater: '공연 예술 극장',
  sculpture: '조각상',

  // 🎓 교육
  library: '도서관',
  preschool: '유치원',
  primary_school: '초등학교',
  school: '학교',
  secondary_school: '중고등학교',
  university: '대학교',

  // 🎉 엔터테인먼트 및 여가
  adventure_sports_center: '어드벤처 스포츠 센터',
  amphitheatre: '야외극장',
  amusement_center: '놀이 시설',
  amusement_park: '놀이공원',
  aquarium: '수족관',
  banquet_hall: '연회장',
  barbecue_area: '바베큐장',
  botanical_garden: '식물원',
  bowling_alley: '볼링장',
  casino: '카지노',
  childrens_camp: '어린이 캠프',
  comedy_club: '코미디 클럽',
  community_center: '커뮤니티 센터',
  concert_hall: '콘서트 홀',
  convention_center: '컨벤션 센터',
  cultural_center: '문화 센터',
  cycling_park: '자전거 공원',
  dance_hall: '댄스홀',
  dog_park: '애견 공원',
  event_venue: '이벤트 장소',
  ferris_wheel: '대관람차',
  garden: '정원',
  hiking_area: '등산로',
  historical_landmark: '역사적 명소',
  internet_cafe: '인터넷 카페',
  karaoke: '노래방',
  marina: '마리나 (요트 정박지)',
  movie_rental: '비디오 대여점',
  movie_theater: '영화관',
  national_park: '국립공원',
  night_club: '나이트클럽',
  observation_deck: '전망대',
  off_roading_area: '오프로드 지역',
  opera_house: '오페라 하우스',
  park: '공원',
  philharmonic_hall: '필하모닉 홀',
  picnic_ground: '피크닉 장소',
  planetarium: '천문관',
  plaza: '광장',
  roller_coaster: '롤러코스터',
  skateboard_park: '스케이트보드 공원',
  state_park: '주립공원',
  tourist_attraction: '관광 명소',
  video_arcade: '비디오 게임장',
  visitor_center: '방문자 센터',
  water_park: '워터파크',
  wedding_venue: '웨딩 장소',
  wildlife_park: '야생동물 공원',
  wildlife_refuge: '야생동물 보호구역',
  zoo: '동물원',

  // 🛁 목욕/위생
  public_bath: '공중목욕탕',
  public_bathroom: '공중화장실',
  stable: '마구간',

  // 💰 금융
  accounting: '회계사무소',
  atm: '현금자동입출금기',
  bank: '은행',

  // 🍽️ 식음료
  acai_shop: '아사이 전문점',
  afghani_restaurant: '아프가니스탄 음식점',
  african_restaurant: '아프리카 음식점',
  american_restaurant: '미국 음식점',
  asian_restaurant: '아시아 음식점',
  bagel_shop: '베이글 가게',
  bakery: '빵집',
  bar: '바',
  bar_and_grill: '바 & 그릴',
  barbecue_restaurant: '바베큐 음식점',
  brazilian_restaurant: '브라질 음식점',
  breakfast_restaurant: '아침식사 전문점',
  brunch_restaurant: '브런치 레스토랑',
  buffet_restaurant: '뷔페 레스토랑',
  cafe: '카페',
  cafeteria: '구내식당',
  candy_store: '사탕 가게',
  cat_cafe: '고양이 카페',
  chinese_restaurant: '중식당',
  chocolate_factory: '초콜릿 공장',
  chocolate_shop: '초콜릿 가게',
  coffee_shop: '커피숍',
  confectionery: '과자점',
  deli: '델리',
  dessert_restaurant: '디저트 음식점',
  dessert_shop: '디저트 가게',
  diner: '다이너',
  dog_cafe: '강아지 카페',
  donut_shop: '도넛 가게',
  fast_food_restaurant: '패스트푸드점',
  fine_dining_restaurant: '고급 레스토랑',
  food_court: '푸드코트',
  french_restaurant: '프랑스 음식점',
  greek_restaurant: '그리스 음식점',
  hamburger_restaurant: '햄버거 가게',
  ice_cream_shop: '아이스크림 가게',
  indian_restaurant: '인도 음식점',
  indonesian_restaurant: '인도네시아 음식점',
  italian_restaurant: '이탈리아 음식점',
  japanese_restaurant: '일식당',
  juice_shop: '주스 전문점',
  korean_restaurant: '한식당',
  lebanese_restaurant: '레바논 음식점',
  meal_delivery: '식사 배달',
  meal_takeaway: '포장 음식점',
  mediterranean_restaurant: '지중해 음식점',
  mexican_restaurant: '멕시코 음식점',
  middle_eastern_restaurant: '중동 음식점',
  pizza_restaurant: '피자 가게',
  pub: '펍',
  ramen_restaurant: '라멘집',
  restaurant: '레스토랑',
  sandwich_shop: '샌드위치 가게',
  seafood_restaurant: '해산물 음식점',
  spanish_restaurant: '스페인 음식점',
  steak_house: '스테이크 하우스',
  sushi_restaurant: '스시집',
  tea_house: '찻집',
  thai_restaurant: '태국 음식점',
  turkish_restaurant: '터키 음식점',
  vegan_restaurant: '비건 음식점',
  vegetarian_restaurant: '채식 음식점',
  vietnamese_restaurant: '베트남 음식점',
  wine_bar: '와인 바',

  // 🗺️ 지역
  administrative_area_level_1: '광역 행정구역',
  administrative_area_level_2: '기초 행정구역',
  country: '국가',
  locality: '지역',
  postal_code: '우편번호',
  school_district: '학군',

  // 🏛️ 정부기관
  city_hall: '시청',
  courthouse: '법원',
  embassy: '대사관',
  fire_station: '소방서',
  government_office: '정부 기관',
  local_government_office: '지방 정부청',
  neighborhood_police_station: '파출소',
  police: '경찰서',
  post_office: '우체국',

  // 🏥 의료
  chiropractor: '척추지압사',
  dental_clinic: '치과 클리닉',
  dentist: '치과',
  doctor: '의사',
  drugstore: '약국',
  hospital: '병원',
  massage: '마사지',
  medical_lab: '의학 실험실',
  pharmacy: '약국',
  physiotherapist: '물리치료사',
  sauna: '사우나',
  skin_care_clinic: '피부 클리닉',
  spa: '스파',
  tanning_studio: '태닝 스튜디오',
  wellness_center: '웰니스 센터',
  yoga_studio: '요가 스튜디오',

  // 🏠 주택
  apartment_building: '아파트 건물',
  apartment_complex: '아파트 단지',
  condominium_complex: '콘도 단지',
  housing_complex: '주거 단지',

  // 🛏️ 숙박시설
  bed_and_breakfast: '민박',
  budget_japanese_inn: '저가 일본 여관',
  campground: '캠핑장',
  camping_cabin: '캠핑 캐빈',
  cottage: '코티지',
  extended_stay_hotel: '장기 체류 호텔',
  farmstay: '농가 민박',
  guest_house: '게스트하우스',
  hostel: '호스텔',
  hotel: '호텔',
  inn: '여관',
  japanese_inn: '일본식 여관',
  lodging: '숙소',
  mobile_home_park: '이동 주택 단지',
  motel: '모텔',
  private_guest_room: '개인 게스트룸',
  resort_hotel: '리조트 호텔',
  rv_park: 'RV 공원',

  // 🌊 자연 지물
  beach: '해변',

  // ⛪ 예배 장소
  church: '교회',
  hindu_temple: '힌두교 사원',
  mosque: '모스크',
  synagogue: '유대교 회당',

  // 🧰 서비스
  astrologer: '점성술사',
  barber_shop: '이발소',
  beautician: '미용사',
  beauty_salon: '미용실',
  body_art_service: '바디 아트 서비스',
  catering_service: '케이터링 서비스',
  cemetery: '묘지',
  child_care_agency: '보육 기관',
  consultant: '컨설팅 서비스',
  courier_service: '택배 서비스',
  electrician: '전기기사',
  florist: '꽃집',
  food_delivery: '음식 배달',
  foot_care: '발 관리',
  funeral_home: '장례식장',
  hair_care: '헤어 관리',
  hair_salon: '헤어 살롱',
  insurance_agency: '보험 대리점',
  laundry: '세탁소',
  lawyer: '변호사',
  locksmith: '자물쇠 수리공',
  makeup_artist: '메이크업 아티스트',
  moving_company: '이사 서비스',
  nail_salon: '네일 살롱',
  painter: '도장공',
  plumber: '배관공',
  psychic: '영매',
  real_estate_agency: '부동산 중개소',
  roofing_contractor: '지붕 시공업체',
  storage: '보관소',
  summer_camp_organizer: '여름 캠프 주최자',
  tailor: '재단사',
  telecommunications_service_provider: '통신 서비스 제공자',
  tour_agency: '투어 에이전시',
  tourist_information_center: '관광 안내소',
  travel_agency: '여행사',
  veterinary_care: '수의사 진료소',

  // 🛍️ 쇼핑
  asian_grocery_store: '아시안 식료품점',
  auto_parts_store: '자동차 부품 상점',
  bicycle_store: '자전거 상점',
  book_store: '서점',
  butcher_shop: '정육점',
  cell_phone_store: '휴대폰 상점',
  clothing_store: '의류 매장',
  convenience_store: '편의점',
  department_store: '백화점',
  discount_store: '할인매장',
  electronics_store: '전자제품 상점',
  food_store: '식료품점',
  furniture_store: '가구점',
  gift_shop: '선물 가게',
  grocery_store: '식료품점',
  hardware_store: '철물점',
  home_goods_store: '생활용품점',
  home_improvement_store: '홈 인테리어 매장',
  jewelry_store: '보석가게',
  liquor_store: '주류 판매점',
  market: '시장',
  pet_store: '애완동물 상점',
  shoe_store: '신발 가게',
  shopping_mall: '쇼핑몰',
  sporting_goods_store: '스포츠용품점',
  store: '상점',
  supermarket: '슈퍼마켓',
  warehouse_store: '창고형 매장',
  wholesaler: '도매상',

  // 🏟️ 스포츠
  arena: '경기장',
  athletic_field: '운동장',
  fishing_charter: '낚시 선박 대여',
  fishing_pond: '낚시터',
  fitness_center: '헬스장',
  golf_course: '골프장',
  gym: '체육관',
  ice_skating_rink: '아이스링크',
  playground: '놀이터',
  ski_resort: '스키장',
  sports_activity_location: '스포츠 활동 장소',
  sports_club: '스포츠 클럽',
  sports_coaching: '스포츠 코칭',
  sports_complex: '스포츠 복합시설',
  stadium: '스타디움',
  swimming_pool: '수영장',

  // 🚉 교통
  airport: '공항',
  airstrip: '활주로',
  bus_station: '버스 터미널',
  bus_stop: '버스 정류장',
  ferry_terminal: '페리 터미널',
  heliport: '헬리포트',
  international_airport: '국제공항',
  light_rail_station: '경전철역',
  park_and_ride: '환승 주차장',
  subway_station: '지하철역',
  taxi_stand: '택시 승강장',
  train_station: '기차역',
  transit_depot: '교통 센터',
  transit_station: '환승역',
  truck_stop: '트럭 휴게소',
};
  
  export const location_types = (type: string): string => {
    return placeTypeMap[type] ?? '기타';
  }
  