'use client'

import { useEffect } from 'react'
// import type { Metadata } from "next";
import "./globals.css"
import { QueryClientProvider, QueryClient } from "@tanstack/react-query"
import Header from '@/common/header/page'
import Footer from '@/common/footer/page'
import Modal from '@/app/modal'
import { modalUiStateAtom } from '@/store/ai'
import { useAtom } from 'jotai'

const queryClient = new QueryClient()

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [aiImodalUiStatenput, _] = useAtom(modalUiStateAtom);

  const shouldDisableScroll = Object.values(aiImodalUiStatenput).some((state) => state);

  const getScrollbarWidth = () => {
    return window.innerWidth - document.documentElement.clientWidth;
  };

  useEffect(() => {
    if (shouldDisableScroll) {
      const scrollbarWidth = getScrollbarWidth();
      document.body.style.overflow = "hidden";
      document.body.style.marginRight = `${scrollbarWidth}px`;
    } else {
      document.body.style.overflow = "auto";
      document.body.style.marginRight = "0px";
    }

    return () => {
      document.body.style.overflow = "auto";
      document.body.style.marginRight = "0px";
    };
  }, [shouldDisableScroll]);

  
  return (
    <QueryClientProvider client={queryClient}>
    <html lang="en">
      <body>
        {/* <div id="global-modal"></div> */}
        <Modal />
        <Header /> 
        {children}
        <Footer />
      </body>
    </html>
    </QueryClientProvider>
  );
}
