'use client'
// import type { Metadata } from "next";
import "./globals.css"
import { QueryClientProvider, QueryClient } from "@tanstack/react-query"
import Header from '@/app/header/page'
import Footer from '@/app/footer/page'

const queryClient = new QueryClient()

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryClientProvider client={queryClient}>
    <html lang="en">
      <body>
        <div id="global-modal"></div>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
    </QueryClientProvider>
  );
}
