import type { Metadata } from "next"
import "./globals.css"
import Header from "@/common/header/page"
import Footer from "@/common/footer/page"
import Modal from "@/modal"
import QueryClientProvider from "@/config/provider/queryClientProvider"
import { ScrollController } from "@/util/scrollController"
import { Suspense } from "react"

export const metadata: Metadata = {
  title: "TripAI",
  description: "Generated by create next app",
  icons: {
    icon: "/img/favicon.PNG"
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={<></>}>
        <QueryClientProvider>
          {/* <div id="global-modal"></div> */}
          <Modal />
          <ScrollController />
          <Header />
          {children}
          <Footer />
        </QueryClientProvider>
        </Suspense>
      </body>
    </html>
  )
}
